version: 0.2
env:
  variables:
    REGION: "ca-central-1"
    IMAGE_REPO: "public.ecr.aws/k0e1e8b3/ericxyan/aws-demo"
    IMAGE_TAG: "latest"
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Logging into AWS ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $IMAGE_REPO
  build:
    commands:
      - mvn install
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $IMAGE_REPO:$IMAGE_TAG
cache:
  paths:
    - "/root/.m2/**/*"
